# -*- after-save-hook: org-latex-export-to-pdf; -*-
#+latex_header: \usepackage[margin=2cm]{geometry}
#+latex_header: \DeclareMathOperator{\sign}{sign}

* Linguagens formais
** Alfabetos
   Um alfabeto é denotado por $\Sigma$. Exemplos:
   #+begin_export latex
   \begin{align*}
     & \Sigma = \{\, 0, 1 \,\} \\
     & \Sigma = \{\, \text{a}, \text{b}, \text{c}, \text{d}, \text{e} \,\} \\
     & \Sigma = \{\, \triangle, \text{O}, \square, \text{X} \,\}
   \end{align*}
   #+end_export
** Palavras
   Uma palavra (ou cadeia) é uma sequência de zero ou mais símbolos do alfabeto.
   @@latex:\\[5pt]@@
   Notação:
   #+begin_export latex
   \begin{align*}
     & \lambda = \varnothing \\
     & 0^4 = 0000 \\
     & \Sigma^3 = \{ 000, 001, 010, 011, 100, 101, 110, 111 \} \\
     & \Sigma^* = \bigcup_{i \in \mathbb{N}} \Sigma^i \quad \text{conjunto de todas as possíveis palavras deste alfabeto.}
   \end{align*}
   #+end_export
   Concatenação:
   #+begin_export latex
   \begin{align*}
     & x = 00 \\
     & y = 11 \\
     & xy = 0011
   \end{align*}
   #+end_export
   Reverso:
   #+begin_export latex
   \[
     (xy)^{\text{R}} = 1100
   \]
   #+end_export
   Observação: uma palavra $w$ é um palíndromo se, e somente se $w^{\text{R}} = w$.
** Linguagens
   Uma linguagem é um conjunto de palavras $L \subseteq \Sigma^*$.
*** Operações
    #+begin_export latex
    \[ L_1L_2 = \{\, xy \,\mid\, x \in L_1,\, y \in L_2 \,\} \\ \]
    \begin{align*}
      & L^0 = \{\, \lambda \,\} \\
      & L^1 = L \\
      & L^2 = LL \\
      & L^* = \bigcup_{i \in \mathbb{N}} L^i \quad \text{Fecho de Kleene} \\
      & L^+ = \bigcup_{i \in \mathbb{N}^*} L^i \\
      & \varnothing^* = \{\, \lambda \,\} \\
      & \varnothing^+ = \varnothing
    \end{align*}
    #+end_export
** Autômatos
   Um autômato finito determinístico é definido por:
   #+begin_export latex
   \begin{align*}
     & Q && \text{Um conjunto finito de estados.} \\
     & \Sigma && \text{Um alfabeto finito.} \\
     & \delta: Q \times \Sigma \to Q && \text{Uma função de transição.} \\
     & q_o \in Q && \text{Um estado inicial.} \\
     & F \subseteq Q && \text{Um conjunto de estados finais.}
   \end{align*}
   #+end_export
   Notação:
   #+begin_export latex
   \begin{align*}
     & L(M) = A \qquad \text{A linguagem reconhecida pelo autômato $M$.} \\[5pt]
     & L(M: F = \varnothing) = \varnothing \\[5pt]
     & \hat{\delta}(e, w): \text{aplicação sucessiva de }\delta\text{ aos símbolos de }w.
   \end{align*}
   #+end_export
*** Computação
    Seja $M = (Q,\, \Sigma,\, \delta,\, q_0,\, F)$ um autômato finito, e $w \in \Sigma^*$.
    Dizemos que $M$ aceita $w$ se existe uma *sequência* de estados
    $r_1, \,\hdots,\, r_n \in Q$ satisfazendo:
    1. $r_0 = q_0$
    2. $\forall\, i \in [0, n): \delta(r_i,\, w_{i + 1}) = r_{i + 1}$
    3. $r_n \in F$
    Um autômato $M$ reconhece uma linguagem $L$ se $\forall\, w \in L: M \text{ aceita } w$. \\
    Uma linguagem é regular se existe um autômato finito que a reconhece.
*** Minimização de estados
    Dois estados $e$ e $e'$ são *equivalentes* se
    #+begin_export latex
    \[
      \hat{\delta}(e, w) \in F \iff \hat{\delta}(e', w) \in F
    \]
    #+end_export
    O algoritmo de minimização, então, é:
    1. Produza uma partição $\mathcal{P}_0 = \{F,\, Q - F\}$ do conjunto de estados $Q$,
       em que os estados finais estão separados dos não finais.
    2. Para cada bloco de estados $B$ na partição $\mathcal{P}_i$, cada símbolo $s$ do
       alfabeto $\Sigma$, e cada par de estados ($e$, $e'$) contidos no bloco B:
       a. Sejam $d = \delta(e, s)$ e $d' = \delta(e' , s)$ os estados para os quais o AFD
          transita quando lê o sı́mbolo $s$ a partir dos estados $e$ e $e'$, respectivamente.
       b. Se $d$ e $d'$ pertencem a blocos diferentes na partiçãoo $\mathcal{P}_i$, então
          os estados $e$ e $e'$ não são equivalentes, e devem ser separados na partição
          $\mathcal{P}_{i+1}$.
    3. Se a partição $\mathcal{P}_{i+1}$ for diferente da partiçãoo $\mathcal{P}_i$,
       repita o passo 2.
    4. O autômato mínimo é construído de tal forma que seus estados são os blocos da
       última partição $\mathcal{P}$ produzida.
