# -*- after-save-hook: org-latex-export-to-pdf; -*-
#+latex_header: \usepackage[margin=2cm]{geometry}
#+latex_header: \DeclareMathOperator{\sign}{sign}
#+latex_header: \setlength{\parindent}{0cm}

* Linguagens formais
** Alfabetos
   Um alfabeto é denotado por $\Sigma$. Exemplos:
   #+begin_export latex
   \begin{align*}
     & \Sigma = \{\, 0, 1 \,\} \\
     & \Sigma = \{\, \text{a}, \text{b}, \text{c}, \text{d}, \text{e} \,\} \\
     & \Sigma = \{\, \triangle, \text{O}, \square, \text{X} \,\}
   \end{align*}
   #+end_export
** Palavras
   Uma palavra (ou cadeia) é uma sequência de zero ou mais símbolos do alfabeto.
   @@latex:\\[5pt]@@
   *Notação*:
   #+begin_export latex
   \begin{align*}
     & \lambda = \varnothing \\
     & 0^4 = 0000 \\
     & \Sigma^3 = \{ 000, 001, 010, 011, 100, 101, 110, 111 \} \\
     & \Sigma^* = \bigcup_{i \in \mathbb{N}} \Sigma^i \quad \text{conjunto de todas as possíveis palavras deste alfabeto.}
   \end{align*}
   #+end_export
   *Concatenação*:
   #+begin_export latex
   \begin{align*}
     & x = 00 \\
     & y = 11 \\
     & xy = 0011
   \end{align*}
   #+end_export
   *Reverso*:
   #+begin_export latex
   \[
     (xy)^{\text{R}} = 1100
   \]
   #+end_export
   Observação: uma palavra $w$ é um palíndromo se, e somente se $w^{\text{R}} = w$.
** Linguagens
   Uma linguagem é um conjunto de palavras $L \subseteq \Sigma^*$. @@latex:\\[5pt]@@
   *Operações*:
   #+begin_export latex
   \[ L_1L_2 = \{\, xy \,\mid\, x \in L_1,\, y \in L_2 \,\} \\ \]
   \begin{align*}
     & L^0 = \{\, \lambda \,\} \\
     & L^1 = L \\
     & L^2 = LL \\
     & L^* = \bigcup_{i \in \mathbb{N}} L^i \quad \text{Fecho de Kleene} \\
     & L^+ = \bigcup_{i \in \mathbb{N}^*} L^i \\
     & \varnothing^* = \{\, \lambda \,\} \\
     & \varnothing^+ = \varnothing
   \end{align*}
   #+end_export
* Autômatos
** Determinísticos
   Um autômato finito determinístico é definido por:
   #+begin_export latex
   \begin{align*}
     & Q && \text{Um conjunto finito de estados.} \\
     & \Sigma && \text{Um alfabeto finito.} \\
     & \delta: Q \times \Sigma \to Q && \text{Uma função de transição.} \\
     & q_o \in Q && \text{Um estado inicial.} \\
     & F \subseteq Q && \text{Um conjunto de estados finais.}
   \end{align*}
   #+end_export
   *Notação*:
   #+begin_export latex
   \begin{align*}
     & L(M) = A \qquad \text{A linguagem reconhecida pelo autômato $M$.} \\[5pt]
     & L(M: F = \varnothing) = \varnothing \\[5pt]
     & \hat{\delta}(e, w): \text{aplicação sucessiva de }\delta\text{ aos símbolos de }w.
   \end{align*}
   #+end_export
*** Computação
    Seja $M = (Q,\, \Sigma,\, \delta,\, q_0,\, F)$ um autômato finito determinístico, e $w
    \in \Sigma^*$. @@latex:\\@@
    Dizemos que $M$ aceita $w$ se existe uma *sequência* de estados
    $r_1, \,\hdots,\, r_n \in Q$ satisfazendo:
    1. $r_0 = q_0$
    2. $\forall\, i \in [0, n): \delta(r_i,\, w_{i + 1}) = r_{i + 1}$
    3. $r_n \in F$
    Um autômato $M$ reconhece uma linguagem $L$ se $\forall\, w \in L: M \text{ aceita } w$. \\
    Uma linguagem é regular se existe um autômato finito que a reconhece.
*** Minimização de estados
    Dois estados $e$ e $e'$ são *equivalentes* se
    #+begin_export latex
    \[
      \hat{\delta}(e, w) \in F \iff \hat{\delta}(e', w) \in F
    \]
    #+end_export
    O algoritmo de minimização, então, é:
    1. Produza uma partição $P_0 = \{F,\, Q - F\}$ do conjunto de estados $Q$,
       em que os estados finais estão separados dos não finais.
    2. Para cada bloco de estados $B$ na partição $#+latex_header: \set[margin=2cm]{geometry}P_i$, cada símbolo $s$ do
       alfabeto $\Sigma$, e cada par de estados ($e$, $e'$) contidos no bloco B:
       a. Sejam $d = \delta(e, s)$ e $d' = \delta(e' , s)$ os estados para os quais o AFD
          transita quando lê o sı́mbolo $s$ a partir dos estados $e$ e $e'$, respectivamente.
       b. Se $d$ e $d'$ pertencem a blocos diferentes na partiçãoo $P_i$, então
          os estados $e$ e $e'$ não são equivalentes, e devem ser separados na partição
          $P_{i+1}$.
    3. Se a partição $P_{i+1}$ for diferente da partiçãoo $P_i$,
       repita o passo 2.
    4. O autômato mínimo é construído de tal forma que seus estados são os blocos da
       última partição $P$ produzida.
** Não determinísticos
   Um autômato finito determinístico é definido por:
   #+begin_export latex
   \begin{align*}
     & Q && \text{Um conjunto finito de estados.} \\
     & \Sigma && \text{Um alfabeto finito.} \\
     & \delta: Q \times \Sigma \to \mathcal{P}(Q) && \text{Uma função de transição.} \\
     & I \subseteq Q && \text{Um conjunto de estados iniciais.} \\
     & F \subseteq Q && \text{Um conjunto de estados finais.}
   \end{align*}
   #+end_export
   Ainda, no AFN existe um estado especial, denonimado $\emptyset$, para o qual não se
   transita. @@latex:\\@@
   Sendo $a \in \Sigma$ um símbolo, e $w \in \Sigma^*$ uma palavra, define-se a função de
   transição estendida:
   #+begin_export latex
   \begin{align*}
     & \hat{\delta}(\emptyset,\, w) = \{\emptyset\} \\[5pt]
     & \hat{\delta}(X,\, \lambda) = X \\[5pt]
     & \hat{\delta}(X,\, aw) = \hat{\delta}\left(\,\bigcup_{l \in X} \delta(l,\, a),\, w \right)
   \end{align*}
   #+end_export
   *Teorema*: Todo AFN possui um AFD equivalente. @@latex:\\@@
   Por construção:
   #+begin_export latex
   \begin{align*}
     & Q = \mathcal{P}(Q_{\text{afn}}) && \\
     & \Sigma = \Sigma_{\text{afn}} && \\
     & \delta(X, a) = \bigcup_{l \in X} \delta_{\text{afn}}(l,\, a) && \\
     & q_o = I_{\text{afn}} && \\
     & F = \left\{ X \subseteq Q_{\text{afn}} \,\mid\, X \cap F \neq \varnothing \right\}&&
   \end{align*}
   #+end_export
*** Transições $\lambda$
    Um autômato finito não determinístico com transições $\lambda$ introduz a
    possibilidade de transições sem a consumação de símbolos.
